FROM node

WORKDIR /app/server

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install -g dotenv-cli
RUN npm install -g dotenv
RUN npm install -g cross-env

RUN npm i -g prisma
RUN npm ci --force

COPY ./ ./

ENV DATABASE_URL=postgresql://postgres:123456@3.35.207.45:5432/postgres
ENV PORT=9898
ENV HOST=3.35.207.45
ENV REDIS_PORT=6379
ENV REDIS_HOST=ljh-redis
ENV JWT_SECRET=ljhcommunity
ENV JWT_ACCESS_SECRET=jwtAccessSecret
ENV JWT_ACCESS_EXPIRE_IN=1000s
ENV JWT_REFRESH_SECRET=jwtRefreshSecret
ENV JWT_REFRESH_EXPIRE_IN=10000s
ENV BCRYPT_SOLT_NUMBER=12345
ENV NODE_ENV=production

ARG AWSACCESSKEYID
ARG AWSSECRETACCESSKEY
ARG AWSREGION
ARG S3BUCKETNAME

ENV AWSACCESSKEYID=${AWSACCESSKEYID}
ENV AWSSECRETACCESSKEY=${AWSSECRETACCESSKEY}
ENV AWSREGION=${AWSREGION}
ENV S3BUCKETNAME=${S3BUCKETNAME}

RUN echo "AWSACCESSKEYID=$AWSACCESSKEYID" \
    && echo "AWSSECRETACCESSKEY=$AWSSECRETACCESSKEY" \
    && echo "AWSREGION=$AWSREGION" \
    && echo "S3BUCKETNAME=$S3BUCKETNAME"

RUN rm -rf ./dist || true
RUN prisma generate
RUN npm run build

CMD ["npm", "run", "start:prod"]
